### DISCUSSION TITLE
Welcome to imixs-workflow Discussions!

### DISCUSSION THREAD

**Discussion by rsoika** [imixs/imixs-workflow#720] [Show and tell]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by frednforester** [comment]
Hi all,
 My name is Fred. been a developer for 40 years. currently tasked with evaluating workflow engines. stumbled across imixs and here I am trying to figure out how to make it work :)

https://www.youtube.com/@SecureWithZephon

hopefully once I figure it out I can make a few videos for others.

let the fun begin!!

**Reply by rsoika** [reply]
Hi @frednforester , thanks for your interest in our workflow technology. A good starting point is our [Quick-Start-Page](https://www.imixs.org/doc/quickstart.html) that gives you an overview how to get started. Imixs-Workflow offers a lot of modules and technologies and so it is a question about what you want to achieve. Maybe the [Imixs-Forms](https://www.imixs.org/doc/webforms/index.html) project is the most easiest way to get a first look.

**Comment by frednforester** [comment]
Hi @rsoika, 
thanks for the welcome.  yep been through the docs. it took a bit of messing around but I was able to get the process manager docker working and the micro services. I noticed the process manager by itself doesn't have the admin app or the openapi-ui in the process manager docker. is that correct or did I just miss it?

Thanks

**Reply by rsoika** [reply]
Yes you are right, only the micro-service project comes with the openapi-ui. Good point, we should add this feature to the other projects too.

**Comment by frednforester** [comment]
Hi Ralph,
I built both war files then copied them to a target dir. and built the image. see below
I modified the root context for both apps to /admin and /pm
they both fire up but when I try to connect to the api via the admin I get auth errors but can login fine to the PM and can run the api in a different window after logging in. it only fails when trying to connect inside the container. I'm going to go take a look at that code shortly checking to see if you know what this could be.

Thanks in advance.

```
mixs-app-1  | 16:30:39,335 INFO  [org.imixs.application.admin.ConnectionController] (default task-5) ...connecting: http://localhost:8080/pm/api
imixs-app-1  | 16:30:39,337 INFO  [org.imixs.application.admin.ConnectionController] (default task-5) init new worklfow client
imixs-app-1  | 16:30:39,446 ERROR [stderr] (default task-5) org.imixs.melman.RestAPIException: Error 401 - failed GET request from 'http://localhost:8080/pm/api/model'
imixs-app-1  | 16:30:39,448 ERROR [stderr] (default task-5)     at deployment.imixs-admin.war//org.imixs.melman.FormAuthenticator.computeLoginURL(FormAuthenticator.java:283)
```

```
FROM quay.io/wildfly/wildfly:27.0.1.Final-jdk11

LABEL description="Imixs-Process-Manager"
LABEL maintainer="ralph.soika@imixs.com"

# Copy EclipseLink and Postgres Driver
COPY ./imixs-process-manager/docker/configuration/wildfly/modules/ /opt/jboss/wildfly/modules/

# Setup configuration
COPY ./imixs-process-manager/docker/configuration/wildfly/*.properties /opt/jboss/wildfly/standalone/configuration/
COPY ./imixs-process-manager/docker/configuration/wildfly/standalone.xml /opt/jboss/wildfly/standalone/configuration/

# Deploy artefact
ADD ./target/*.war /opt/jboss/wildfly/standalone/deployments/
WORKDIR /opt/jboss/wildfly
# Run with management interface
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]

---- build image with 2 war files
cp ./imixs-process-manager/target/imixs-process-manager.war ./target
cp ./imixs-admin/target/imixs-admin.war ./target
```

```
#docker build -f Docker.zephon -t imixs-zephon ./
docker build -f Dockerfile-wildfly -t imixs-zephon ./
```

------------------------------------------------------
compose file

```yaml
version: "3.6"
services:

  imixs-db:
    image: postgres:13.11
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow-db
    volumes:
      - dbdata:/var/lib/postgresql/data

  imixs-app:
    image: imixs-zephon:latest
    environment:
      TZ: "CET"
      LANG: "en_US.UTF-8"
      JAVA_OPTS: "-Dnashorn.args=--no-deprecation-warning"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://imixs-db/workflow-db"
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
volumes:
  dbdata:
```

--------------------------------------------------------------
run the image
docker compose -f imixs-zephon.yml up
