### DISCUSSION TITLE
Intergrating Postfix with Imixs-Office-Workflow

### DISCUSSION THREAD

**Discussion by lazo23** [imixs/imixs-workflow#842] [Q&A]
Hello @rsoika,

I'm interested in integrating Postfix with imixs-Office-Workflow to enable email sending from within the workflow system to specified email accounts. Can someone provide guidance on how to achieve this integration and share the necessary configuration steps?

Thank you for your assistance.

**Comment by rsoika** [comment]
Hi,
this is independent from the Imixs-Office-Workflow application.
You can setup your smarthost and than you only need to provide an environment variable. In the standalone.xml  file we have the following setting:

```
        <outbound-socket-binding name="mail-smtp">
            <remote-destination host="${env.MAILGATEWAY}" port="25"/>
        </outbound-socket-binding>
```

So when you set MAILGATEWAY to your postfix server sending mails should work.

**Reply by lazo23** [reply]
Hi @rsoika,

where do I find the standalone.xml file? I am running Imixs-Office-Workflow via Docker. 

Thank you, Lazo

**Reply by rsoika** [reply]
In case you are using the standard docker setup is is sufficient if you just add the environment variable MAILGATEWAY

```yaml
...
  app:
    image: imixs/imixs-office-workflow
    depends_on:
      - db
    environment:
      TZ: "CET"
      LANG: "en_US.UTF-8"
      MAILGATEWAY: "your-postfix-host"
      ....
```

Note, that the expected port is the default smtp-port 25
