### ISSUE TITLE
SetupService - provide new method to scan a model directory

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-workflow#917]
provide new alternatively method to scan a model directory for model and xml files.

Example Setup 

```yaml
  app:
    image: imixs/imixs-microservice
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/workflow"
      MODEL_DEFAULT_DATA: "/home/imixs/model/"
      MODEL_DEFAULT_DATA_OVERWRITE: "true"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    volumes:
      - ./workflow/:/home/imixs/model/
```
